djangpapp/urls.py
from django.contrib import admin
from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

# from django.contrib import admin  
# from django.urls import path  
# from AddressBook import views  
  
# urlpatterns = [  
#     path('admin/', admin.site.urls),  
#     path('hello/', views.hello),  
# ]  

# from django.contrib import admin  
# from django.urls import path  
from AddressBook import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('index/', views.index), 
    # path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),   
]  

AddressBook/models.py
from __future__ import unicode_literals  
from django.db import models  
# from django.db import models

# Create your models here.
# from django.db import models  
  
class Users(models.Model):  
    user_id = models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length=30)  
    last_name = models.CharField(max_length=30)
    DOB = models.DateField()
    mobile =  models.IntegerField(unique=True)
    email  = models.EmailField(max_length=50,unique=True)
    city = models.CharField(max_length=30)  
    state = models.CharField(max_length=30)
    country = models.CharField(max_length=30)  
    pin = models.IntegerField()
    user_name = models.CharField(max_length=20,unique=True)  
    password = models.CharField(max_length=30)
    class Meta:  
        db_table = "Users"   
        
    

AddressBook/views.py
from django.shortcuts import render

# Create your views here.
# from django.shortcuts import render  
  
# Create your views here.  
# from django.http import HttpResponse  
  
# def hello(request):  
#     return HttpResponse("<h2>Hello, Welcome to Django-Adress Book created by joy!</h2>")  
# from django.shortcuts import render  
from AddressBook.form import UseForm  
*for normal viewing  
def index(request):  
    Use = UseForm()  
    return render(request,"index.html",{'form':Use})  


#**for validations
# def index(request):  
#     if request.method == "POST":  
#         form = UseForm(request.POST)  
#         if form.is_valid():  
#             try:  
#                 return redirect('/')  
#             except:  
#                 pass  
#     else:  
#         form = UseForm()  
#     return render(request,'index.html',{'form':UseForm})  

from django.shortcuts import render, redirect  
from AddressBook.form import UseForm  
from AddressBook.models import Users  
# Create your views here.  
def index(request):  
    if request.method == "POST":  
        form = UseForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = UseForm()  
    return render(request,'index.html',{'form':UseForm})  
def show(request):  
    users = Users.objects.all()  
    return render(request,"show.html",{'users':users})  
def edit(request, id):  
    users = Users.objects.get(id=id)  
    return render(request,'edit.html', {'users':users})    
def update(request, id):  
    users = Users.objects.get(id=id)  
    form = UseForm(request.POST, instance = users)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'users':users})  
def destroy(request, id):  
    users = Users.objects.get(id=id)  
    users.delete()  
    return redirect("/show")  

AddressBook/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{users.user_id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">User id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="user_id" id="id_user_id" required maxlength="20" value="{{ users.user_id }}"/>  
    </div>
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">First Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="first_name" id="id_first_name" required maxlength="100" value="{{ users.first_name }}" />  
    </div> 
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Last Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="last_name" id="id_last_name" required maxlength="100" value="{{ users.last_name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Date Of Birth:</label>  
    <div class="col-sm-4">  
        <input type="text" name="DOB" id="id_DOB" required maxlength="100" value="{{ users.DOB }}" />  
    </div>  
 
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">City:</label>  
    <div class="col-sm-4">  
        <input type="text" name="city" id="id_city" required maxlength="100" value="{{ users.city }}" />  
    </div>   
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">State:</label>  
    <div class="col-sm-4">  
        <input type="text" name="state" id="id_state" required maxlength="100" value="{{ users.state }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Country:</label>  
    <div class="col-sm-4">  
        <input type="text" name="country" id="id_country" required maxlength="100" value="{{ users.country }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Pincode:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pin" id="id_pin" required maxlength="100" value="{{ users.pin }}" />  
    </div> 
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="email" id="id_email" required maxlength="254" value="{{ users.email }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Mobile:</label>  
    <div class="col-sm-4">  
        <input type="text" name="mobile" id="id_mobile" required maxlength="15" value="{{ users.mobile }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

AddressBook/templates/index.html
<!-- <!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
</head>  
<body>  
<form method="POST" class="post-form">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <button type="submit" class="save btn btn-default">Save</button>  
    </form>  
</body>  
</html>   -->



<!-- <!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
</head>  
<body>  
<form method="POST" class="post-form" enctype="multipart/form-data">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <button type="submit" class="save btn btn-default">Save</button>  
</form>  
</body>  
</html>   -->

<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/index">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">User id:</label>  
    <div class="col-sm-4">  
      {{ form.user_id }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">First Name:</label>  
    <div class="col-sm-4">  
      {{ form.first_name }}  
    </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Last Name:</label>  
    <div class="col-sm-4">
     {{ form.last_name }}  
    </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Date Of Birth:</label>  
    <div class="col-sm-4">  
      {{ form.DOB }}  
    </div>
     
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Email:</label>  
    <div class="col-sm-4">  
      {{ form.email }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Mobile:</label>  
    <div class="col-sm-4">  
      {{ form.mobile }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">City:</label>  
    <div class="col-sm-4">  
      {{ form.city }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">State:</label>  
    <div class="col-sm-4">  
      {{ form.state }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Country:</label>  
    <div class="col-sm-4">  
      {{ form.country }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Pincode:</label>  
    <div class="col-sm-4">  
      {{ form.pin }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Username:</label>  
    <div class="col-sm-4">  
      {{ form.user_name }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">password:</label>  
    <div class="col-sm-4">  
      {{ form.password }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

AddressBook/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>User Records</title>  
     {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>User id</th>  
        <th>First Name</th>  
        <th>Last Name</th>
        <th>Date Of Birth</th>
        <th>Email</th>
        <th>Mobile</th>
        <th>City</th> 
        <th>State</th>
        <th>Country</th>
        <th>Pincode</th>
        <th>Username</th>
        <th>password</th>          
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for users in Users %}  
    <tr>  
        <td>{{ users.user_id }}</td>  
        <td>{{ users.first_name }}</td>  
        <td>{{ users.last_name }}</td>  
        <td>{{ users.DOB }}</td>
        <td>{{ users.mobile }}</td>
        <td>{{ users.email }}</td>
        <td>{{ users.city }}</td>
        <td>{{ users.state }}</td>
        <td>{{ users.country }}</td>
        <td>{{ users.pin }}</td>
        <td>{{ users.user_name }}</td>
        <td>{{ users.password }}</td>
        <td>  
            <a href="/edit/{{ users.user_id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ users.user_id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/index" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  